---
title: "Supplementary Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Supplementary Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message = FALSE}
library(ggplot2)
library(plotly)
library(dplyr)
library(colorspace)
library(dittoSeq)
library(tidySingleCellExperiment)
library(tidygate)

sce_obj <- bioc2022tidytranscriptomics::sce_obj
```


Instead of filtering using a specified threshold, the gamma delta T cells could be interactively selected from the plot using the tidygate package.

```{r eval = FALSE}
sce_obj |>

  join_features(
    features = c("CD3D", "TRDC", "TRGC1", "TRGC2", "CD8A", "CD8B" ), shape = "wide"
  ) |>

  mutate(signature_score =
           scales::rescale(CD3D + TRDC + TRGC1+ TRGC2, to=c(0,1)) -
           scales::rescale(CD8A + CD8B, to=c(0,1))
  ) |>

  mutate(gate = gate_int(
    UMAP_1, UMAP_2,
    .size = 0.1,
    .color =signature_score
  ))

```

After the selection we could reload from a file the gate that was drawn, for reproducibility.

```{r}
sce_obj |>

  join_features(
    features = c("CD3D", "TRDC", "TRGC1", "TRGC2", "CD8A", "CD8B" ), shape = "wide"

  ) |>

  mutate(signature_score =
           scales::rescale(CD3D + TRDC + TRGC1+ TRGC2, to=c(0,1)) -
           scales::rescale(CD8A + CD8B, to=c(0,1))
  ) |>

  mutate(gate = gate_int(
    UMAP_1, UMAP_2,
    .size = 0.1,
    .color =signature_score,
    gate_list = bioc2022tidytranscriptomics::gate_sce_obj
  ))

```

The dataset can be filtered for just these cells using tidyverse `filter`.

```{r}
sce_obj_gamma_delta <-
    
  sce_obj |>

  join_features(
    features = c("CD3D", "TRDC", "TRGC1", "TRGC2", "CD8A", "CD8B" ), shape = "wide"

  ) |>

  mutate(signature_score =
           scales::rescale(CD3D + TRDC + TRGC1+ TRGC2, to=c(0,1)) -
           scales::rescale(CD8A + CD8B, to=c(0,1))
  ) |>

  mutate(gate = gate_int(UMAP_1, UMAP_2, gate_list = bioc2022tidytranscriptomics::gate_sce_obj)) |>

  filter(gate == 1)
```
